### ISSUE TITLE
AttributeError: 'list' object has no attribute 'nodeIds'

### ISSUE THREAD

**Issue by mrzapp** [vvoovv/blender-geo#112]
Hi there, just bought the premium version.
Thanks for the work you put into this!

I am getting this error when importing a region covering Copenhagen:

```
Traceback (most recent call last):
  File "/home/mrzapp/.config/blender/2.79/scripts/addons/blender-osm/__init__.py", line 153, in execute
    return self.importOsm(context)
  File "/home/mrzapp/.config/blender/2.79/scripts/addons/blender-osm/__init__.py", line 224, in importOsm
    a.process()
  File "/home/mrzapp/.config/blender/2.79/scripts/addons/blender-osm/app/__init__.py", line 370, in process
    m.process()
  File "/home/mrzapp/.config/blender/2.79/scripts/addons/blender-osm/building/manager.py", line 151, in process
    bvhTree = self.createBvhTree()
  File "/home/mrzapp/.config/blender/2.79/scripts/addons/blender-osm/building/manager.py", line 181, in createBvhTree
    polygon = element.getData(osm) if element.t is Renderer.polygon else element.getOuterData(osm)
  File "/home/mrzapp/.config/blender/2.79/scripts/addons/blender-osm/parse/relation/multipolygon.py", line 353, in getData
    return self.getLinestringData(self.ls, osm)
  File "/home/mrzapp/.config/blender/2.79/scripts/addons/blender-osm/parse/relation/multipolygon.py", line 369, in getLinestringData
    return (osm.nodes[nodeId].getData(osm) for nodeId in linestring.nodeIds(osm))
AttributeError: 'list' object has no attribute 'nodeIds'

location: <unknown location>:-1
```

These are my settings:
![image](https://user-images.githubusercontent.com/2747428/49287916-797cce80-f49f-11e8-9b46-69c833f841db.png)

![image](https://user-images.githubusercontent.com/2747428/49287943-8d283500-f49f-11e8-9dea-fcbfaa870167.png)

I tried restarting Blender

Blender version 2.79b
Plugin version 1.0.1.0
Python version 3.7.1

**Comment by mrzapp** [comment]
I got the same error with New York as the location, so it's not just Copenhagen.

**Comment by vvoovv** [comment]
Thank you very much for purchasing the blender-osm addon!

Please ensure that you use the official stable release from https://www.blender.org/download/
Other builds often cause strange and unexplainable errors.

Please inform if that helped to solve the problem.

**Comment by mrzapp** [comment]
Aha, that did the trick :) Thanks!
