### ISSUE TITLE
Does not work when import "image overlay", Blender 2.8, 5/14/19

### ISSUE THREAD

**Issue by ParaArchi** [vvoovv/blender-geo#122]
The following error code appears when press on image overlay> import.
Same applies to Mapbox Satellite, OSM Mapnik & Mapbox Streets
________________________________________
bpy.context.scene.blender_osm.dataType = 'overlay'
bpy.ops.blender_osm.import_data()
Traceback (most recent call last):
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-osm\__init__.py", line 456, in modal
    if app.app.overlay.finalizeImport():
  File "C:\Users\Home\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\blender-osm\overlay\__init__.py", line 194, in finalizeImport
    image.pack(as_png=True)
TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)

location: <unknown location>:-1
________________________________________

**Comment by plankatron** [comment]
i am getting a similar issue when trying to import overlays 

Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 456, in modal
    if app.app.overlay.finalizeImport():
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/overlay/__init__.py", line 194, in finalizeImport
    image.pack(as_png=True)
TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by vvoovv** [comment]
Thank you for reporting the issue!

The Blender developers have broken the Python API recently. The problem shows up in the very recent daily releases of the Blender 2.80

I'll fix it soon as possible.

**Comment by vvoovv** [comment]
The problem has been fixed. Also some other issues caused by Python API breaks in the Blender 2.80 have been fixed.

Please use the link in your purchase confirmation e-mail to download the latest version of the blender-osm (premium),

**Comment by vvoovv** [comment]
Please let me know if the addon works for you now.

**Comment by plankatron** [comment]
so i redownloaded the osm premium and it may be the same version? i get the same exact error and actually now i also get errors with importing openstreetmap data onto a terrain.

osm version 1.0.15

**Comment by vvoovv** [comment]
@plankatron 
Please restart Blender.
The version of the  addon is the right one (1.0.15)

If there is an error, please send the full error text.

**Comment by plankatron** [comment]
sorry for the long paste , this also shows openstreet map import failing at first and then image overlay failing as well
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 489, in drawMessage
    message = app.app.stateMessage
AttributeError: 'App' object has no attribute 'stateMessage'
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 456, in modal
    if app.app.overlay.finalizeImport():
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/overlay/__init__.py", line 194, in finalizeImport
    if _isBlender280:
TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)

location: <unknown location>:-1

location: <unknown location>:-1
Info: Saved "heaven-mountain1.blend"

Read blend: /home/fleeky/3d/pacifica-data/heaven-mountain1.blend
Info: Read library:  '/media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', '//../../../../media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', parent '<direct>'
Info: Read library:  '/media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', '//../../../../media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', parent '<direct>'

Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 456, in modal
    if app.app.overlay.finalizeImport():
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/overlay/__init__.py", line 194, in finalizeImport
    if _isBlender280:
TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)

location: <unknown location>:-1

location: <unknown location>:-1
Info: Saved "heaven-mountain1.blend"

Downloading the file from http://overpass-api.de/api/map?bbox=-122.5411605834961,37.560768127441406,-122.4414291381836,37.60742950439453...
Saving the file to /media/fleeky/7AF9ADA258906B06/openstreetdata/osm/map_4.osm...
Parsing OSM file /media/fleeky/7AF9ADA258906B06/openstreetdata/osm/map_4.osm...
Time for parsing OSM file: 0:00:01.091932
Processing the parsed OSM data...
The number of buildings: 5542
Time for processing of the parsed OSM data: 0:00:00.046222
Creating meshes in Blender...
Info: Removed 0 vertices
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 165, in execute
    return self.importOsm(context)
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 241, in importOsm
    a.render()
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/app/__init__.py", line 489, in render
    m.render()
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/building/manager.py", line 151, in render
    self.renderer.render(building, self.osm)
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/building/renderer.py", line 123, in render
    self.preRender(outline)
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/renderer/__init__.py", line 87, in preRender
    parent = None if _isBlender280 else self.parent
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/renderer/__init__.py", line 190, in createBlenderObject
    collection.objects.link(obj)
ReferenceError: StructRNA of type Collection has been removed

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 456, in modal
    if app.app.overlay.finalizeImport():
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/overlay/__init__.py", line 194, in finalizeImport
    if _isBlender280:
TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)

location: <unknown location>:-1

location: <unknown location>:-1
Read blend: /home/fleeky/3d/pacifica-data/heaven-mountain.blend
Info: Read library:  '/media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', '//../../../../media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', parent '<direct>'
Info: Read library:  '/media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', '//../../../../media/fleeky/7AF9ADA258906B06/openstreetdata/assets/building_materials.blend', parent '<direct>'

Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/io_kmat_export.py", line 300, in draw
    ko = mat.kmat_opts
AttributeError: 'NoneType' object has no attribute 'kmat_opts'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/io_kmat_export.py", line 300, in draw
    ko = mat.kmat_opts
AttributeError: 'NoneType' object has no attribute 'kmat_opts'

location: <unknown location>:-1

location: <unknown location>:-1
Info: Deleted 1 object(s)

Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/io_kmat_export.py", line 299, in draw
    mat = context.active_object.active_material
AttributeError: 'NoneType' object has no attribute 'active_material'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/io_kmat_export.py", line 300, in draw
    ko = mat.kmat_opts
AttributeError: 'NoneType' object has no attribute 'kmat_opts'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/io_kmat_export.py", line 300, in draw
    ko = mat.kmat_opts
AttributeError: 'NoneType' object has no attribute 'kmat_opts'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/io_kmat_export.py", line 300, in draw
    ko = mat.kmat_opts
AttributeError: 'NoneType' object has no attribute 'kmat_opts'

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/io_kmat_export.py", line 300, in draw
    ko = mat.kmat_opts
AttributeError: 'NoneType' object has no attribute 'kmat_opts'

location: <unknown location>:-1

location: <unknown location>:-1
Info: Saved "heaven-mountain.blend"

Info: Deleted 3 object(s)

Downloading the file from http://overpass-api.de/api/map?bbox=-122.53807067871094,37.5660514831543,-122.45974731445312,37.60335159301758...
Saving the file to /media/fleeky/7AF9ADA258906B06/openstreetdata/osm/map_5.osm...
Parsing OSM file /media/fleeky/7AF9ADA258906B06/openstreetdata/osm/map_5.osm...
Time for parsing OSM file: 0:00:01.123778
Processing the parsed OSM data...
The number of buildings: 5375
Time for processing of the parsed OSM data: 0:00:00.118369
Creating meshes in Blender...
Info: Removed 0 vertices
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 165, in execute
    return self.importOsm(context)
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 241, in importOsm
    a.render()
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/app/__init__.py", line 489, in render
    m.render()
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/building/manager.py", line 151, in render
    self.renderer.render(building, self.osm)
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/building/renderer.py", line 123, in render
    self.preRender(outline)
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/renderer/__init__.py", line 87, in preRender
    parent = None if _isBlender280 else self.parent
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/renderer/__init__.py", line 190, in createBlenderObject
    collection.objects.link(obj)
ReferenceError: StructRNA of type Collection has been removed

location: <unknown location>:-1

location: <unknown location>:-1
Traceback (most recent call last):
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/__init__.py", line 456, in modal
    if app.app.overlay.finalizeImport():
  File "/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/overlay/__init__.py", line 194, in finalizeImport
    if _isBlender280:
TypeError: Image.pack(): was called with invalid keyword argument(s) (as_png), expected (data, data_len)

location: <unknown location>:-1

location: <unknown location>:-1

**Comment by vvoovv** [comment]
@plankatron 
The error looks very odd.
The line 194 in the file `/home/fleeky/.config/blender/2.80/scripts/addons/blender-osm/overlay/__init__.py` is
`if _isBlender280:`
However it complains about the call `Image.pack()`

Please try to restart Blender or even reboot your computer

**Comment by ParaArchi** [comment]
Thank you! it works!

**Comment by woodengun** [comment]
Hi. Im getting the same error as above when adding the image overlay for the terrain (set to mapbox sattelite) :

Traceback (most recent call last):

RuntimeError: Error: Cannot pack edited image from disk, only as internal PNG

location: <unknown location>:-1

Im using the latest OSM plugin version (1.0.15)

I am using Blender 2.8. I tried restarting and rebooting. Im on an older Mac Osx. Any suggestions?
Other than this, its a great addon! thanks!

**Comment by vvoovv** [comment]
@woodengun 
Thank you for reporting the problem!
It's a different error. I've created a separate issue #124 for that problem. Please use the new issue #124 to post messages
