### ISSUE TITLE
StructRNA of type Collection has been removed

### ISSUE THREAD

**Issue by JakeLeyser** [vvoovv/blender-geo#146]
So, I just found your awesome work OSM and thought to give it a try but I'm getting this error whenever I try to import  OpenStreetMap data... The terrain data seems to work fine, please help

```
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-osm\__init__.py", line 175, in execute
    return self.importOsm(context)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-osm\__init__.py", line 252, in importOsm
    a.render()
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-osm\app\__init__.py", line 488, in render
    m.render()
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-osm\building\manager.py", line 151, in render
    self.renderer.render(building, self.osm)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-osm\building\renderer.py", line 123, in render
    self.preRender(outline)
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-osm\renderer\__init__.py", line 87, in preRender
    parent = None if _isBlender280 else self.parent
  File "C:\Users\admin\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\blender-osm\renderer\__init__.py", line 190, in createBlenderObject
    collection.objects.link(obj)
ReferenceError: StructRNA of type Collection has been removed

location: <unknown location>:-1
```

**Comment by vvoovv** [comment]
Try to restart Blender.

**Comment by JakeLeyser** [comment]
Restarting worked, thanks... I feel dumb now...
