### ISSUE TITLE
AttributeError: 'Way' object has no attribute 'hasInner'

### ISSUE THREAD

**Issue by guilindner** [vvoovv/blender-geo#147]
Hi, on a fresh installation (Blender 2.82) I got the following error
```

Error: Traceback (most recent call last):
  File "/home/guinux/.config/blender/2.82/scripts/addons/blender-osm/__init__.py", line 175, in execute
    return self.importOsm(context)
  File "/home/guinux/.config/blender/2.82/scripts/addons/blender-osm/__init__.py", line 252, in importOsm
    a.render()
  File "/home/guinux/.config/blender/2.82/scripts/addons/blender-osm/app/__init__.py", line 488, in render
    m.render()
  File "/home/guinux/.config/blender/2.82/scripts/addons/blender-osm/building/manager.py", line 151, in render
    self.renderer.render(building, self.osm)
  File "/home/guinux/.config/blender/2.82/scripts/addons/blender-osm/building/renderer.py", line 134, in render
    self.renderElement(outline, building, osm)
  File "/home/guinux/.config/blender/2.82/scripts/addons/blender-osm/building/renderer.py", line 152, in renderElement
    if element.hasInner():
AttributeError: 'Way' object has no attribute 'hasInner'

location: <unknown location>:-1
```
It doesn't matter if I use 3D realistic, 3D simple or 2D. Makes no difference using import from File or Server either.

Anyone with the same issue?

**Comment by vvoovv** [comment]
Please send the OSM file that causes the error to prokitektura@gmail.com or attach it here.

**Comment by vvoovv** [comment]
The problem was discussed via e-mail.
The cause of the problem is much likely in the different Python versions in the official Blender release and custom Blender builds.
I'll investigate which Python code behave differently in Python 3.7 and Python 3.8.

The official Blender release from https://www.blender.org/download/ should be used for now.

**Comment by vvoovv** [comment]
solved
