### ISSUE TITLE
Can´t import Forests... Why?

### ISSUE THREAD

**Issue by ThatsHero** [vvoovv/blender-geo#225]
location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C:\Users\chef\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-osm\__init__.py", line 165, in execute
    return self.importOsm(context)
  File "C:\Users\chef\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-osm\__init__.py", line 242, in importOsm
    a.render()
  File "C:\Users\chef\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-osm\app\__init__.py", line 493, in render
    m.renderExtra()
  File "C:\Users\chef\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-osm\realistic\manager.py", line 82, in renderExtra
    layer.renderer.finalizeBlenderObject(layer, app)
  File "C:\Users\chef\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-osm\realistic\renderer.py", line 164, in finalizeBlenderObject
    bpy.ops.object.modifier_apply(apply_as='DATA', modifier="Boolean")
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\bpy\ops.py", line 201, in __call__
    ret = op_call(self.idname_py(), None, kw)
TypeError: Converting py args to operator properties: : keyword "apply_as" unrecognized

location: <unknown location>:-1

**Comment by vvoovv** [comment]
Please update the addon, since Blender developer made some changes in the Python API in Blender 2.90.
