### ISSUE TITLE
[Feature Request] Downloading administratory borders

### ISSUE THREAD

**Issue by Mi-Pe** [vvoovv/blender-geo#230]
[Feature Request]
Hello!
Is it possible to download administratory borders with this plugin? I mean city, municipality, district, land, voivodeship etc. borders. If not, could it be added in the future as an option? They are normally available from OSM.

**Comment by vvoovv** [comment]
Did you mean if it's possible to display the borders in Blender?

**Comment by Mi-Pe** [comment]
Yes, I mean get them from OSM and display as an object, like roads, lands, buildings etc. :)

**Comment by vvoovv** [comment]
I need more time to think about it. There are some tricky issues.

**Comment by Mi-Pe** [comment]
I can wait if there is a chance you can add it :D

**Comment by Mi-Pe** [comment]
Perhaps you could use BlenderGIS source code as an example because the author already implemented this feature. Still, I prefer your addon because it lets me import far larger area and is technically not problematic, while I had issues with BlenderGIS.

**Comment by vvoovv** [comment]
> I can wait if there is a chance you can add it :D

I hope so.

**Comment by vvoovv** [comment]
You mentioned voivodeships... Here they are:

![image](https://user-images.githubusercontent.com/613295/99131345-ed302b80-2623-11eb-8363-367a4f2d43be.png)

Details will follow.

**Comment by Mi-Pe** [comment]
Looks cool! I'm mostly interested in cities, districts and municipalities/ counties.

**Comment by vvoovv** [comment]
> I'm mostly interested in cities, districts and municipalities/ counties.

In Poland?

**Comment by Mi-Pe** [comment]
Yes, in Poland mainly but I thought it could be done as a universal feature that future users from all round the world will be able to use. I don't want to waste your time for simply getting some piece of data for me. I'd prefer "a rod than a fish", as they say ;)

Ok, only now I realized that each country has probably its own system for administratory borders in OSM. But I think there is a common definition of all administratory borders for the entire world, called "boundaries: administrative". I'm referring to this resource:
wiki.openstreetmap.org/wiki/Map_Features
"An administrative boundary. Subdivisions of areas/territories/jurisdictions recognised by governments or other organisations for administrative purposes. These range from large groups of nation states right down to small administrative districts and suburbs, as indicated by the 'admin_level=*' combo tag. "

**Comment by vvoovv** [comment]
I am ready to describe the solution. It requires a manual download of OSM data. But I think it isn't that difficult.

**Comment by vvoovv** [comment]
Download and install the latest version (2.4.28 or above) of the addon.

Switch to the _3D simple_ mode in the addon panel

Uncheck all OpenStreetMap "layers" (buildings, roads, water, etc) since they aren't available in the OSM data sets to be downloaded.

Set the value of the _Import from_ option to _file_.

Uncheck the option _Import as a single object_.

Download the setup script [base_borders.py](https://raw.githubusercontent.com/vvoovv/blender-osm/setup_scripts/base_borders.py) and set the path to it in the field _Setup script_.

Note that the default geographical projection used by the addon (transverse Mercator) is good to import cities, towns and other inhabited dwellings. Administrative borders may span a huge area and a different geographical projection might be appropriate for you case. See [here](https://github.com/vvoovv/blender-osm/wiki/Documentation#custom-map-projections) how to use a custom geographical projection with the Blender-OSM addon.

**Comment by vvoovv** [comment]
To be continued

**Comment by vvoovv** [comment]
Administrative borders are typically mapped with the tags [boundary=administrative](https://wiki.openstreetmap.org/wiki/Tag:boundary%3Dadministrative) and [admin_level](https://wiki.openstreetmap.org/wiki/Key:admin_level). It's importand to understand them. It's also important to know which [admin_level](https://wiki.openstreetmap.org/wiki/Key:admin_level) is appropriate for you case.

Many administrative borders are also mapped with the tag [place](https://wiki.openstreetmap.org/wiki/Key:place). For some cities, towns and other inhabited dwellings it's the only tag used to mark the their borders.

**Comment by vvoovv** [comment]
Polish administrative border will be used as an example.

Poland is divided into a number of voivodeship (an equivalent of province). Each voivodeship is divided into a number of counties.

**Comment by vvoovv** [comment]
### Task 1. Import administrative boundaries of all polish voivodeships (provinces).

First we need to get the OpenStreetMap _id_ of the country border of Poland. It's needed to limit the query within Poland.

Type _Poland_ in the search box at [osm.org](https://www.openstreetmap.org) and press _Enter_. Find the entry for the country boundary of Poland in the search result list and press it. You should see the text _Relation: Poland (49715)_ on the left top corner of the resulting page with the address https://www.openstreetmap.org/relation/49715.

49715 is the OpenStreetMap _id_ of the country border of Poland. It will be needed in the next step.

Open the page http://overpass-turbo.eu.

Paste the text request to the field on the left side:
```
[out:xml];
relation(area:3600000000)["boundary"="administrative"]["admin_level"="4"];
(._;>;);
out meta;
```
Note that [admin_level](https://wiki.openstreetmap.org/wiki/Key:admin_level)=4 is used for the borders of provinces.

Replace the number _3600000000_ for the sum of _3600000000_ and the boundaries _id_. In our example the boundaries _id_ is 49715, then the sum would be 3600049715 and the resulting request would be
```
[out:xml];
relation(area:3600049715)["boundary"="administrative"]["admin_level"="4"];
(._;>;);
out meta;
```

Now execute the resulting request.
Press _Export -> Data -> raw data directly from Overpass API -> done_

Save the file with the extension _.osm_.

Now you can import the file into Blender with the help of _Blender-OSM_ addon.

**Comment by vvoovv** [comment]
### Task 2. Import administrative boundaries of a specific polish voivodeship (province)

Lublin Voivodeship will be used as an example.

The borders can be queried by the value of the OpenStreetMap tag _name_. Type _Lublin Voivodeship_ in the search box at [osm.org](https://www.openstreetmap.org) and press Enter. Find the entry for the state boundary of Lublin Voivodeship and press it. Find a row for the tag _name_ in the table _Tags_ in the resulting page https://www.openstreetmap.org/relation/130919.

The value of the tag _name_ is _województwo lubelskie_. It will be needed in the next step.

Open the page http://overpass-turbo.eu.

Paste the text request to the field on the left side:
```
[out:xml];
relation["boundary"="administrative"]["admin_level"="4"]["name"="województwo lubelskie"];
(._;>;);
out meta;
```
Note that [admin_level](https://wiki.openstreetmap.org/wiki/Key:admin_level)=4 is used for the borders of provinces.

Now execute the resulting request.
Press _Export -> Data -> raw data directly from Overpass API -> done_

Save the file with the extension _.osm_.

Now you can import the file into Blender with the help of _Blender-OSM_ addon.

**Comment by vvoovv** [comment]
### Task 3. Import administrative boundaries of all counties within a specific polish voivodeship (province)

Borders of all counties within Lublin Voivodeship will be imported in the example below.

First we need to get the OpenStreetMap _id_ of the state border of Lublin Voivodeship. It's needed to limit the query within Lublin Voivodeship.

Type _Lublin Voivodeship_ in the search box at [osm.org](https://www.openstreetmap.org) and press Enter. Find the entry for the state boundary of Lublin Voivodeship and press it. You should see the text _Relation: Lublin Voivodeship (130919)_ on the left top corner of the resulting page with the address https://www.openstreetmap.org/relation/130919.

130919 is the OpenStreetMap _id_ of the state border of Lublin Voivodeship. It will be needed in the next step.

Open the page http://overpass-turbo.eu.

Paste the text request to the field on the left side:
```
[out:xml];
relation(area:3600000000)["boundary"="administrative"]["admin_level"="6"];
(._;>;);
out meta;
```
Note that [admin_level](https://wiki.openstreetmap.org/wiki/Key:admin_level)=6 is used for the borders of counties.

Replace the number _3600000000_ for the sum of _3600000000_ and the boundaries _id_. In our example the boundaries _id_ is 130919, then the sum would be 3600130919 and the resulting request would be
```
[out:xml];
relation(area:3600130919)["boundary"="administrative"]["admin_level"="6"];
(._;>;);
out meta;
```

Now execute the resulting request.
Press _Export -> Data -> raw data directly from Overpass API -> done_

Save the file with the extension _.osm_.

Now you can import the file into Blender with the help of _Blender-OSM_ addon.

**Comment by vvoovv** [comment]
### Task 4. Import of the borders of New York City

If the name of a city is unique in the world, its borders can be simply queried by the value of the OpenStreetMap tag _name_.

Open the page http://overpass-turbo.eu.

Paste the text request to the field on the left side:
```
[out:xml];
relation["place"="city"]["name"="New York"];
(._;>;);
out meta;
```

Now execute the resulting request.
Press _Export -> Data -> raw data directly from Overpass API -> done_

Save the file with the extension _.osm_.

Now you can import the file into Blender with the help of _Blender-OSM_ addon.

**Comment by Mi-Pe** [comment]
Thank you for the instructions but I didn't succeed. I downloaded the "Raw data directly from Overpass API" and it got saved as a file without extension. I added ".osm" extension and tried to import it after setting your addon as you instructed but I'm getting this error:

"
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-osm\__init__.py", line 188, in execute
    return self.importOsm(context)
  File "C:\Users\Dell\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\blender-osm\__init__.py", line 282, in importOsm
    self.setCenterLatLon(context, osm.lat, osm.lon)
AttributeError: 'Osm' object has no attribute 'lat'

location: <unknown location>:-1
"

Well, I'm still seeking for a simple way of downloading boundaries as just another layer next to: buildings, water objects, forests etc. Perfectly, one would just select an area as we always do to get all layers, and one of these layers would be boundaries - be it city, county, provice, country or any other type of boundary, that will fall into selected area. Would you consider implementing such workflow, or the one you described, into the core of your plugin?

**Comment by Mi-Pe** [comment]
What does this error mean? Did I make a typo mistake when querying data from overpass-turbo.eu? I don't think so because the site itself would throw an error but it didn't.

**Comment by vvoovv** [comment]
It could be a bug.
Could you please send me the code of your resulting request for overpass-turbo.eu?
You could send it to prokitektura@gmail.com if you don't want to expose some private information.

**Comment by vvoovv** [comment]
> Well, I'm still seeking for a simple way of downloading boundaries as just another layer next to: buildings, water objects, forests etc. Perfectly, one would just select an area as we always do to get all layers, and one of these layers would be boundaries - be it city, county, provice, country or any other type of boundary, that will fall into selected area. Would you consider implementing such workflow, or the one you described, into the core of your plugin?

If you think the needed borders are contained in your OSM data set, set the _Setup script_ to _base_borders.py_ in the _3D simple_ mode and that's it.

The problem is that Blender can't handle millions of buildings located even in a middle size country or province. That's why the borders for larger areas (e.g. countries, provinces) should be downloaded separately.

**Comment by Mi-Pe** [comment]
> If you think the needed borders are contained in your OSM data set, set the Setup script to base_borders.py in the 3D simple mode and that's it.
>

Amazing! This is exactly what I needed! Could you implement this little script to the core of your plugin so that we can download boundaries just as easily as buildings?

I also got rid of error with overpass-turbo.eu method. Had to be my typo or something.

**Comment by vvoovv** [comment]
There was no big demand for that feature so far. So I'd prefer to leave it for the custom setup script.

**Comment by Mi-Pe** [comment]
Sure, I understand. Anyway, thank you very much. You helped me a lot!

**Comment by zanna93** [comment]
Hello!
I'm trying to export from overpass-turbo.eu the administrative borders of some italian municipalities (San Paolo di Jesi, Cupramontana and Staffolo). 
I used this code:

> [out:xml][timeout:90];
> (
>   relation["boundary"="administrative"]["admin_level"="8"]["name"="San Paolo di Jesi"]({{bbox}});
>   relation["boundary"="administrative"]["admin_level"="8"]["name"="Cupramontana"]({{bbox}});
>   relation["boundary"="administrative"]["admin_level"="8"]["name"="Staffolo"]({{bbox}});
> );
> out body;
> >;
> out skel qt;

<img width="945" height="936" alt="Image" src="https://github.com/user-attachments/assets/ce26aab3-fdcc-4a50-9a8a-c3b86d5385f3" />

Then I export API Overpass and I try to import it with your amazing plugin.

First, I rename the downloaded file, adding .osm extension.
<img width="231" height="281" alt="Image" src="https://github.com/user-attachments/assets/ab2b407f-04df-4028-82e8-235acade8e5f" />

Then I go to plugin tab, select that file in "File" box, add your .py script in "Setup script" box, deselect everything as you wrote in this topic, and then click "Import".
<img width="489" height="740" alt="Image" src="https://github.com/user-attachments/assets/a2e0dec0-c50e-4859-91ac-0eb3800ef1e8" />

Unfortunately, it just imports an empty collection, so I guess I'm doing something wrong.
<img width="175" height="28" alt="Image" src="https://github.com/user-attachments/assets/7b8456a0-08f7-413d-a61b-4e67220255e4" />

**Comment by zanna93** [comment]
UPDATE:
I've bought Blosm premium version and now it works!
This is the script I used.

[base_borders2.py](https://github.com/user-attachments/files/23412322/base_borders2.py)
