### ISSUE TITLE
Value error importing 3D (simple and realistic) buildings for a specific region

### ISSUE THREAD

**Issue by Davnos** [vvoovv/blender-geo#245]
Hi,
when importing 3D buildings for the region 11.60517,48.06638,11.65714,48.08757 the following error appears:

Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\__init__.py", line 190, in execute
    return self.importOsm(context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\__init__.py", line 279, in importOsm
    a.render()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\app\__init__.py", line 526, in render
    m.render()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\manager.py", line 146, in render
    self.renderer.render(building, self.osm)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\renderer.py", line 135, in render
    self.renderElement(outline, building, osm)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\renderer.py", line 164, in renderElement
    self._renderElement(element, building, roof, data, osm)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\renderer.py", line 176, in _renderElement
    roof.render()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\roof\__init__.py", line 224, in render
    self.renderRoof()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\roof\__init__.py", line 241, in renderRoof
    for f in (bm.faces.new(verts[i] for i in indices) for indices in self.roofIndices):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\roof\__init__.py", line 241, in <genexpr>
    for f in (bm.faces.new(verts[i] for i in indices) for indices in self.roofIndices):
ValueError: faces.new(...): found the same (BMVert) used multiple times

location: <unknown location>:-1

Blender version: 2.92.0
BlenderOSM version: 2.4.31
Windows 10

**Comment by vvoovv** [comment]
Hi @Davnos 

Thank you for reporting the problem. I'll try to fix it as soon as possible.

**Comment by vvoovv** [comment]
Just for my own reference. Here is the building that causes the error:
https://www.openstreetmap.org/way/267120824

**Comment by vvoovv** [comment]
I hope to fix the problem within a week.

**Comment by vvoovv** [comment]
The problem is fixed. The next release of the addon with the fix will be next week. I'll inform you about it.

**Comment by Davnos** [comment]
Thanks!

**Comment by vvoovv** [comment]
Please download the new release of the addon with the bug fix.
