### ISSUE TITLE
Import Buildings 3d Realistic - Failed - IndexError: list index out of range

### ISSUE THREAD

**Issue by Danielmannn** [vvoovv/blender-geo#246]
After making good experiences with the free version I just bought the pro. Unfortunately I got an error and don't know what is going on. What do I have to do?

Python: Traceback (most recent call last):
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\__init__.py", line 190, in execute
    return self.importOsm(context)
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\__init__.py", line 279, in importOsm
    a.render()
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\app\__init__.py", line 526, in render
    m.render()
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\manager.py", line 146, in render
    self.renderer.render(building, self.osm)
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\renderer.py", line 135, in render
    self.renderElement(outline, building, osm)
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\renderer.py", line 164, in renderElement
    self._renderElement(element, building, roof, data, osm)
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\renderer.py", line 175, in _renderElement
    if roof.make(osm):
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\roof\profile.py", line 620, in make
    slotR.trackUp(roofIndices)
  File "C:\Users\dan thi\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\blender-osm\building\roof\profile.py", line 456, in trackUp
    elif part[-1] != parts[index+1][1][0]:
IndexError: list index out of range

location: <unknown location>:-1

**Comment by vvoovv** [comment]
Hi @Danielmannn 

Thank you for purchasing the premium version.

Please inform us the coordinates of your area of interest. They are needed to reproduce and localize the problem.

**Comment by Danielmannn** [comment]
![grafik](https://user-images.githubusercontent.com/83009280/115703483-77ff1a00-a36a-11eb-8d6f-2fc36df0f996.png)
Paris

**Comment by vvoovv** [comment]
Do you perhaps have a smaller area where the problem occurs? It would help to localize the problem faster.

**Comment by Danielmannn** [comment]
Will try again tomorrow or monday at the latest.

**Comment by vvoovv** [comment]
I hope to fix the problem within a week provided that the building causing the error is found.

**Comment by Danielmannn** [comment]
I tried it again with a smaller part and did not have the problem. I will probably do a couple of exports again over the next weeks and tell you if I find it.

**Comment by vvoovv** [comment]
I didn't search for the building that caused the error. But I fixed a similar problem for another building. I hope your problem will be fixed too. I expect the next release of the addon to happen next week.

**Comment by Danielmannn** [comment]
Nice. I did not try yet cause I am really busy with related stuff and the part I have right now is good enough.

**Comment by vvoovv** [comment]
Please download the new release of the addon with the bug fix.

**Comment by MaxenceColet** [comment]
Hi @vvoovv ! Thank you for your amazing plugin !
I'm having the exact same issue as @Danielmannn and managed to find the building that was causing the error :
`-0.76627,48.07366,-0.76544,48.07447`

**Comment by vvoovv** [comment]
Hi @MaxenceColet,

Thank you for reporting the problem.

I was able to reproduce the problem. It will take 1-2 week to fix it. I'll inform once it's fixed.

**Comment by vvoovv** [comment]
Also https://www.openstreetmap.org/way/630236462

**Comment by vvoovv** [comment]
It will take longer to fix it. But I hope to fix it in June.

**Comment by Boolerex** [comment]
I got the same problem myself in a different area of the map, the problem building should be in the parcel is this coordinate: `-122.46125,37.72002,-122.46024,37.72186`

**Comment by vvoovv** [comment]
Hi @Boolerex 

> I got the same problem myself in a different area of the map, the problem building should be in the parcel is this coordinate: `-122.46125,37.72002,-122.46024,37.72186`

Sorry, I am unable to reproduce the problem. Your area of interest is imported without any problems in all modes.

Which version of the addon do you use?
 
Please attach a screenshot of the error.

**Comment by Boolerex** [comment]
![image](https://user-images.githubusercontent.com/58222145/158095670-438f9f0e-773f-47a3-8b27-cdbb64c98c19.png)

Here a screenshot of the error with the coordinate (not sure I've pasted the right coordinate), I'm in version 2.5.1 for the addon

**Comment by vvoovv** [comment]
I used the same settings as in your screenshot and it works for me fine in Blender 3.1. The version of the addon is 2.5.3.

![image](https://user-images.githubusercontent.com/613295/158146380-666288bd-f2e2-49e6-b76b-17b38df43eea.png)

**Comment by Boolerex** [comment]
Odd, I'm also in blender 3.1, I updated the addon to version 2.5.3 and still got the same error in those coordinate.

I also tried to put the asset package to the default package + put nothing in the terrain field and I'm still getting the same error

**Comment by neis-lotte** [comment]
I have the same issue in the following coordinates : max lat: 52.55762, max lo:13.46460, min lat:52.55627 and min lon:13.46091. Is there a way you could fix that too?

**Comment by vvoovv** [comment]
@neis-lotte 

Ok, there are many reports with this issue.

The first step is to find the problem building.

**Comment by vvoovv** [comment]
@MaxenceColet
@Boolerex
@neis-lotte

You problems are fixed. Please use the latest version of Blosm (currently 2.7.27).

Sorry for the delay with the fix.
