### ISSUE TITLE
How to enable experimental features properly

### ISSUE THREAD

**Issue by yuqianma** [vvoovv/blender-geo#250]
I'm trying the latest premium version (2.5.1). It works perfectly except the experimental features.
When I turned on that flag, tried to import from osm to generate 3D stuffs, it threw error:
```
Python: Traceback (most recent call last):
  File "/Users/.../Library/Application Support/Blender/2.92/scripts/addons/blender-osm/__init__.py", line 201, in execute
    return self.importOsm(context)
  File "/Users/.../Library/Application Support/Blender/2.92/scripts/addons/blender-osm/__init__.py", line 243, in importOsm
    from setup.realistic_dev import setup as setup_function
  File "/Users/.../Library/Application Support/Blender/2.92/scripts/addons/blender-osm/setup/realistic_dev.py", line 1, in <module>
    from style import StyleStore
  File "/Users/.../Library/Application Support/Blender/2.92/scripts/addons/blender-osm/style/__init__.py", line 11, in <module>
    from pml import PML
  File "/Users/.../Library/Application Support/Blender/2.92/scripts/addons/blender-osm/pml/__init__.py", line 1, in <module>
    from antlr4 import InputStream, CommonTokenStream, ParseTreeWalker
ModuleNotFoundError: No module named 'antlr4'

location: <unknown location>:-1

```
I fiddle with the addon's files. There's a `antlr4` folder inside `pml` folder. But import `antlr4` instead of `.antlr4`。It confused me. And I wonder if it is a mac only issue, as I cannot find easy way to install `antlr4` for mac.
So what's the intended way to try exp features? Do I need to solve the dependency by myself? But I have on idea how to install packages inside Blender.

**Comment by vvoovv** [comment]
Does restarting Blender solve the issue?

**Comment by yuqianma** [comment]
> Does restarting Blender solve the issue?

Yes, it does !!!
I've even tried to revise the script, and reload the addon, etc...

BTW, I'm a python & blender newbie. Why `import antlr4` instead of `import .antlr4`  ?

**Comment by vvoovv** [comment]
_antlr4_ is an extrernal library used by the addon.
`import .antlr4` doesn't work.
