### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by DanMcLaughlin** [vvoovv/blender-geo#263]
Hello,
   With the following coordinates have the following crash with latest premium

![image](https://user-images.githubusercontent.com/4943582/132258240-b649179a-e6df-4c33-9cfd-47507e28de01.png)

`Python: Traceback (most recent call last):
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\__init__.py", line 201, in execute
    return self.importOsm(context)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\__init__.py", line 299, in importOsm
    a.render()
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\app\blender.py", line 427, in render
    m.render()
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\building\manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\building2\renderer.py", line 156, in render
    action.do(building, itemClass, buildingStyle, self)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\__init__.py", line 93, in do
    self.generateVolume(footprint, element.getData(self.data))
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\__init__.py", line 100, in generateVolume
    volumeGenerator.do(footprint, coords)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof.py", line 83, in do
    self.render(footprint, roofItem)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof_flat.py", line 22, in render
    self.extrude(footprint, roofItem)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof_flat.py", line 71, in extrude
    facades.extend(
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof_flat.py", line 72, in <genexpr>
    Facade.getItem(
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\item\facade.py", line 49, in getItem
    volumeGenerator.initFacadeItem(item)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof_flat.py", line 89, in initFacadeItem
    item.normal = bottomVec.cross(zAxis)/width
ZeroDivisionError: Vector division: divide by zero error

location: <unknown location>:-1

`

**Comment by DanMcLaughlin** [comment]
Text paste

`-74.02039,40.69938,-73.96653,40.74852`

**Comment by DanMcLaughlin** [comment]
Hm, keep getting this no matter what I do it seems. Blender just updated to 2.93.4, is there an issue with this version? Or something else? Unable to use the plugin today, tried various settings but get divide by zero.  Here's another one

`Python: Traceback (most recent call last):
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\__init__.py", line 201, in execute
    return self.importOsm(context)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\__init__.py", line 299, in importOsm
    a.render()
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\app\blender.py", line 427, in render
    m.render()
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\building\manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\building2\renderer.py", line 156, in render
    action.do(building, itemClass, buildingStyle, self)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\__init__.py", line 65, in do
    self.volumeGeneratorMultiHipped.do(footprint)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof_flat_multi.py", line 14, in do
    self.render(footprint, roofItem)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof_hipped_multi.py", line 49, in render
    ok = self.generateRoof(footprint, roofItem, firstVertIndex)
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\action\volume\roof_hipped_multi.py", line 130, in generateRoof
    polygonize(
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\lib\bpypolyskel\bpypolyskel.py", line 1048, in polygonize
    embedding = graph.circular_embedding(verts,'CCW')
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in circular_embedding
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in <lambda>
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\lib\bpypolyskel\poly2FacesGraph.py", line 18, in compare_angles
    a1 = pseudoangle(vList[p1] - vList[center])
  File "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\lib\bpypolyskel\poly2FacesGraph.py", line 11, in pseudoangle
    p = d[0]/(abs(d[0])+abs(d[1])) # -1 .. 1 increasing with x
ZeroDivisionError: float division by zero

location: <unknown location>:-1

`

**Comment by vvoovv** [comment]
Hi @DanMcLaughlin 

Sorry for the errors. The second error is caused by a different problem. What are the coordinates for the second error?

What is the version of the addon?

**Comment by DanMcLaughlin** [comment]
I just changed the box a bit, -74.02009,40.69938,-73.96653,40.73620

I clicked Import for export I believe, just trying different things 

![image](https://user-images.githubusercontent.com/4943582/132259538-a2e1c375-f276-45c7-a448-193dd10d11d7.png)

**Comment by DanMcLaughlin** [comment]
2.5.1, just updated in fact to make sure before doing anything.

**Comment by DanMcLaughlin** [comment]
Don't mean to pester, but any luck?

**Comment by vvoovv** [comment]
I am going to fix the errors. The first task is to find the buildings that caused the errors.

**Comment by DanMcLaughlin** [comment]
Sounds good thanks

**Comment by vvoovv** [comment]
I tried to find the problem building

> -74.02039,40.69938,-73.96653,40.74852

This area is too big. I was unable to encounter the problem building for a number of hours and then terminated the import.

> I just changed the box a bit, -74.02009,40.69938,-73.96653,40.73620

Actually you changed the area quite significantly. The area size is ok. But the whole import was ok for me. No errors popped up.

I am kindly asking you to help me to identify the problem buildings.

* Open the file "C:\Users\Dan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\blender-osm\building2\renderer.py".
* Uncomment the line [130](https://github.com/vvoovv/blender-osm/blob/release/building2/renderer.py#L130)
* Start the import in the experimental mode. OSM ids of the buildings will be printed to the Blender System Console (Main menu -> Window -> Toggle System Console)
* We need the last printed _id_ before the error text.

**Comment by DanMcLaughlin** [comment]
OK got around to this last night. Yeah the second one isn't causing trouble now either, nor is the first. At least with that line uncommented and experimental mode on. Tag it as unreproducable, perhaps Blender or the add on got into a weird state.
