### ISSUE TITLE
Installation issues in Blender 2.93.5

### ISSUE THREAD

**Issue by bruse** [vvoovv/blender-geo#269]
Hi!

I'm getting some errors when installing the plugin.

Steps:
1. Download plugin from Gumroad
2. Install plugin through Blender UI
3. Enable plugin by clicking the checkbox

Output:
```Modules Installed (blender-osm-3) from '/Users/bruse/Downloads/blender-osm-3.zip' into '/Users/bruse/Library/Application Support/Blender/2.93/scripts/addons'
Traceback (most recent call last):
  File "/Applications/Blender.app/Contents/Resources/2.93/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "/Users/bruse/Library/Application Support/Blender/2.93/scripts/addons/blender-osm-3/__init__.py", line 59, in <module>
    import gui, ape
  File "/Users/bruse/Library/Application Support/Blender/2.93/scripts/addons/blender-osm-3/gui/__init__.py", line 23, in <module>
    from app.blender import app
  File "/Users/bruse/Library/Application Support/Blender/2.93/scripts/addons/blender-osm-3/app/blender.py", line 30, in <module>
    from renderer.curve_layer import CurveLayer
  File "/Users/bruse/Library/Application Support/Blender/2.93/scripts/addons/blender-osm-3/renderer/curve_layer.py", line 23, in <module>
    from util.blender import appendObjectsFromFile, createDiffuseMaterial, createCollection, addShrinkwrapModifier
ImportError: cannot import name 'addShrinkwrapModifier' from 'util.blender' (/Users/bruse/Library/Application Support/Blender/2.93/scripts/addons/blender-osm/util/blender.py)
```

I'm on an Apple Silicon MacBook Pro, if that's at all relevant.

Let me know if you want to pursue this, and if you need any more information from me.

**Comment by vvoovv** [comment]
Hi @bruse 

The first thing to try is restarting Blender.

**Comment by bruse** [comment]
That worked really well!

Thank you :)
