### ISSUE TITLE
Hello, I get an error on my blender as soon as I import some obj models, here is the error in question:

### ISSUE THREAD

**Issue by Singh8946** [vvoovv/blender-geo#301]
Python: Traceback (most recent call last):
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\__init__.py", line 227, in execute
    return self.importTerrain(context)
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\__init__.py", line 385, in importTerrain
    a.importTerrain(context)
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\app\blender.py", line 489, in importTerrain
    minHeight = self.buildTerrain(verts, indices, heightOffset)
  File "C:\Users\ACER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\app\blender.py", line 575, in buildTerrain
    z = struct.unpack('>h', buf)[0]
struct.error: unpack requires a buffer of 2 bytes

location: <unknown location>:-1

**Comment by vvoovv** [comment]
Hi @Singh8946 

Please show me the content (including file sizes) of the folder _[the folder for the addon data]/terrain_.

**Comment by Singh8946** [comment]
https://user-images.githubusercontent.com/83008932/170082441-52a763f0-6132-4d2d-82ed-6c6a70a4687e.mp4

https://user-images.githubusercontent.com/83008932/170082455-3beaec31-5424-464a-8529-5d4aeab7e053.mp4

**Comment by vvoovv** [comment]
In the addon preferences you set  a directory for addon data. I need to see the content (including file sizes) of the subfolder _terrain_ of that directory.

**Comment by Singh8946** [comment]
![Blender File View 24-05-2022 22_56_23](https://user-images.githubusercontent.com/83008932/170090845-9f2c4020-306a-4a38-9ad2-5990f6c96693.png)

**Comment by vvoovv** [comment]
There was a network error in downloading the file _N30E078.hgt.gz_, since it has the size _0_. Please delete it an import your area of interest again. I hope it helps.

**Comment by Singh8946** [comment]
Thank you that you have helped me and if I need any further help, I will let you know.
