### ISSUE TITLE
terrain import - Issue

### ISSUE THREAD

**Issue by Memphis2022** [vvoovv/blender-geo#304]
Hi all,
I received the following error, after trying to import a 8Km square terrain from austria.
Nothing different than usual, but for some reasons, I'm receiving this:
Any feedback would be much appreciated.
Thanks
=============
Python: Traceback (most recent call last):
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\__init__.py", line 203, in execute
    return self.importTerrain(context)
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\__init__.py", line 361, in importTerrain
    a.importTerrain(context)
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\app\blender.py", line 490, in importTerrain
    minHeight = self.buildTerrain(verts, indices, heightOffset)
  File "C:\Users\xxxxxx\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\blender-osm\app\blender.py", line 564, in buildTerrain
    f.seek( 2*((hard_size-y*decimate)*(hard_size+1) + x1*decimate) )
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\gzip.py", line 392, in seek
    return self._buffer.seek(offset, whence)
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\_compression.py", line 143, in seek
    data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\python\lib\gzip.py", line 506, in read
    raise EOFError("Compressed file ended before the "
EOFError: Compressed file ended before the end-of-stream marker was reached

location: <unknown location>:-1

**Comment by vvoovv** [comment]
Hi @Memphis2022 

Probably it was an incomplete download due to some some network problems.

Please attach a screenshot with the content of the subfolder _terrain_ in the directory that you set in the addon preferences to store downloaded OSM and terrain files. I need also to see the size of the files in the subfolder _terrain_.
