### ISSUE TITLE
Error on image overlay import

### ISSUE THREAD

**Issue by HokkaidoInu** [vvoovv/blender-geo#305]
I get this error:

```
Python: Traceback (most recent call last):
  File "C:\Users\cycli\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blosm\__init__.py", line 229, in execute
    return self.importOverlay(context)
  File "C:\Users\cycli\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blosm\__init__.py", line 419, in importOverlay
    a.overlay.prepareImport(minLon, minLat, maxLon, maxLat)
  File "C:\Users\cycli\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blosm\overlay\__init__.py", line 132, in prepareImport
    maxNumTiles * equator * equator / (b-t) / (r-l)
ValueError: math domain error

location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\cycli\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blosm\__init__.py", line 229, in execute
    return self.importOverlay(context)
  File "C:\Users\cycli\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blosm\__init__.py", line 419, in importOverlay
    a.overlay.prepareImport(minLon, minLat, maxLon, maxLat)
  File "C:\Users\cycli\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\blosm\overlay\__init__.py", line 132, in prepareImport
    maxNumTiles * equator * equator / (b-t) / (r-l)
ValueError: math domain error

location: <unknown location>:-1
```

Here is the content of the subfolder terrain in the directory that I set in the addon preferences to store downloaded OSM and terrain files: 
![blosm](https://user-images.githubusercontent.com/78092452/177056833-2156fad9-d137-485b-bd20-b12e436b5ac5.PNG)

**Comment by vvoovv** [comment]
Hi @HokkaidoInu 

Please attach a screenshot with the coordinates of your area of interest.

**Comment by HokkaidoInu** [comment]
I tried many places, so I don't think the location is the problem but this is the last place I tried.
![coords](https://user-images.githubusercontent.com/78092452/177060081-53a7c092-8e88-4dd9-9060-ac069b3e2163.PNG)

**Comment by HokkaidoInu** [comment]
@vvoovv 

I tried many places, so I don't think the location is the problem but this is the last place I tried.
![coords](https://user-images.githubusercontent.com/78092452/177060081-53a7c092-8e88-4dd9-9060-ac069b3e2163.PNG)

**Comment by vvoovv** [comment]
> I tried many places, so I don't think the location is the problem but this is the last place I tried.

I worked for me as expected. Let's do it this way. Save your Blender file after the error popped up and save the Blender file for examination.

**Comment by HokkaidoInu** [comment]
[https://easyupload.io/m/94gcpf](https://easyupload.io/m/94gcpf)

**Comment by HokkaidoInu** [comment]
Ok so I had an old version of blender so I got the latest one and now it works. :)
