### ISSUE TITLE
Failure to Import 3D Buildings - Python Error

### ISSUE THREAD

**Issue by Waffle1434** [vvoovv/blender-geo#336]
Blender 3.4.1
blender-osm Premium (Latest from gumroad)

Attempting to import 3D buildings always fails, python error. Importing 2D works however.
![image](https://user-images.githubusercontent.com/8021358/216881426-f7c5be9a-976d-44dd-8e08-4fb55f6d7503.png)
```
Downloading the file from http://overpass-api.de/api/map?bbox=44.35747146606445,33.22505187988281,44.509220123291016,33.3184814453125...
Saving the file to F:\OSM\osm\map_6.osm...
Parsing OSM file F:\OSM\osm\map_6.osm...
Traceback (most recent call last):
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\__init__.py", line 225, in execute
    return self.importOsm(context)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\__init__.py", line 292, in importOsm
    osm.parse(a.osmFilepath, forceExtentCalculation=forceExtentCalculation)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\parse\osm\__init__.py", line 179, in parse
    complete = relation.process(members, tags, self)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\parse\osm\relation\building.py", line 95, in process
    osm.getRelation(mId, Multipolygon).o = self.outline
AttributeError: 'Building' object has no attribute 'o'
Error: Python: Traceback (most recent call last):
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\__init__.py", line 225, in execute
    return self.importOsm(context)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\__init__.py", line 292, in importOsm
    osm.parse(a.osmFilepath, forceExtentCalculation=forceExtentCalculation)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\parse\osm\__init__.py", line 179, in parse
    complete = relation.process(members, tags, self)
  File "C:\Users\super\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\blender-osm\parse\osm\relation\building.py", line 95, in process
    osm.getRelation(mId, Multipolygon).o = self.outline
AttributeError: 'Building' object has no attribute 'o'
```

**Comment by vvoovv** [comment]
Hi @Waffle1434 

Thank you for reporting the problem. We'll try to reproduce it and come back to you.
