### ISSUE TITLE
Blender OSM - Python Error on Import OpenStreetMap

### ISSUE THREAD

**Issue by cnunesgit** [vvoovv/blender-geo#340]
Hi,

Can't import terrain on Blender OSM.
COuld you please help me?

This is the error I get

Python: Traceback (most recent call last):
  File "/Users/cnunes/Library/Application Support/Blender/3.4/scripts/addons/blosm/__init__.py", line 225, in execute
    return self.importOsm(context)
  File "/Users/cnunes/Library/Application Support/Blender/3.4/scripts/addons/blosm/__init__.py", line 292, in importOsm
    osm.parse(a.osmFilepath, forceExtentCalculation=forceExtentCalculation)
  File "/Users/cnunes/Library/Application Support/Blender/3.4/scripts/addons/blosm/parse/osm/__init__.py", line 94, in parse
    osm = etree.parse(filepath).getroot()
  File "/Applications/Blender.app/Contents/Resources/3.4/python/lib/python3.10/xml/etree/ElementTree.py", line 1222, in parse
    tree.parse(source, parser)
  File "/Applications/Blender.app/Contents/Resources/3.4/python/lib/python3.10/xml/etree/ElementTree.py", line 569, in parse
    source = open(source, "rb")
IsADirectoryError: [Errno 21] Is a directory: '/'

Thank you

**Comment by vvoovv** [comment]
Hi @cnunesgit 

You probably tried importing a folder instead of an OpenStreetMap file.
