### ISSUE TITLE
UnboundLocalError: local variable 'y' referenced before assignment

### ISSUE THREAD

**Issue by sangress** [vvoovv/blender-geo#346]
System Info:

  version: 3.5.0, 
  branch: blender-v3.5-release,
  type: release,
  build date: 2023-03-29, 06:35:04,
  platform: 'macOS-12.5.1-x86_64-i386-64bit',
  (Python) version: Python 3.10.9,
  CPU device capabilities: SSE2 SSE41 AVX2
  plugin version: 2.6.5

When trying to import terrain the plugin throws an exception:
`Python: Traceback (most recent call last):
  File "/Users/sangress/Library/Application Support/Blender/3.5/scripts/addons/blender-osm/__init__.py", line 227, in execute
    return self.importTerrain(context)
  File "/Users/sangress/Library/Application Support/Blender/3.5/scripts/addons/blender-osm/__init__.py", line 388, in importTerrain
    a.importTerrain(context)
  File "/Users/sangress/Library/Application Support/Blender/3.5/scripts/addons/blender-osm/app/blender.py", line 505, in importTerrain
    minHeight = self.buildTerrain(verts, indices, heightOffset)
  File "/Users/sangress/Library/Application Support/Blender/3.5/scripts/addons/blender-osm/app/blender.py", line 645, in buildTerrain
    prevYsize = y2-y
UnboundLocalError: local variable 'y' referenced before assignment`

The 'y' variable is outside of the loop (from line 575) scope.

**Comment by vvoovv** [comment]
Hi @sangress 

I'd like to reproduce the problem. What were the coordinates of your area of interest?
