### ISSUE TITLE
not able to activate plugin in blender 3.5.0

### ISSUE THREAD

**Issue by LisekWindows** [vvoovv/blender-geo#347]
I have this problem help:
Traceback (most recent call last):
  File "C:\Program Files (x86)\Steam\steamapps\common\Blender\3.5\scripts\modules\addon_utils.py", line 369, in enable
    mod.register()
  File "C:\Users\XYZ\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-osm\__init__.py", line 596, in register
    gui.register()
  File "C:\Users\XYZ\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\blender-osm\gui\__init__.py", line 924, in register
    bpy.utils.register_class(c)
RuntimeError: Error: Registering panel class: 'PanelBlosmExtent' has category 'osm'

**Comment by LisekWindows** [comment]
Sorry didn't read for what blender it was
