### ISSUE TITLE
Blender fails to install the osm plug-in, and the prompt is as follows

### ISSUE THREAD

**Issue by Yangxiaobo-123** [vvoovv/blender-geo#411]
Traceback (most recent call last):
File "/Applications/Blender.app/Contents/Resources/3.6/scripts/modules/addon_ utils.py", line 333, in enable
mod =
import (module name)
File "/Users/yangzhibo/Library/Application Support/Blender/3.6/scripts/addons/blosm/_init
•py", line 61, in <module>
import gui, ape
File "/Users/yangzhibo/Library/Application Support/Blender/3.6/scripts/addons/blosm/gui/_initpy", line 23, in <module>
from app.blender import app
File "/Users/yangzhibo/Library/Application Support/Blender/3.6/scripts/addons/blosm/app/blender.py", line 30, in <module>
from renderer.curve _layer import CurveLayer
File "/Users/yangzhibo/Library/Application Support/Blender/3.6/scripts/addons/blosm/renderer/curve layer.py", line 23, in <module>
from til.blender import appendObjectsFromFile, createDiffuseMaterial, createCollection, addShrinkwrapModifier
ImportError: cannot import name "addShrinkwrapModifier' from 'util.blender' (/Users/yangzhibo/Library/Application Support/Blender/3.6/scripts/addons/blender-osm/util/blender.py)

**Comment by Yangxiaobo-123** [comment]
My computer is a mac with m1 chip

**Comment by vvoovv** [comment]
Hi @Yangxiaobo-123 

Please try restarting Blender. If it didn't help, please try the following actions:
* Delete all previous versions of Blender-OSM or Blosm addon. There can be more than one of them. You can find them by typing osm in the search box in the Blender preferences.
* Restart Blender
* Install the latest version of the Blosm addon.

**Comment by svvitch** [comment]
> Hi [@Yangxiaobo-123](https://github.com/Yangxiaobo-123)
> 
> Please try restarting Blender. If it didn't help, please try the following actions:
> 
> * Delete all previous versions of Blender-OSM or Blosm addon. There can be more than one of them. You can find them by typing osm in the search box in the Blender preferences.
> * Restart Blender
> * Install the latest version of the Blosm addon.

This worked.
