### ISSUE TITLE
AttributeError when importing buildings with onion or dome shaped roof

### ISSUE THREAD

**Issue by redactedUse** [vvoovv/blender-geo#421]
As the title says, it's easy to replicate. Either edit a local osm file manually to add a dome or onion roof shape as described [on the openstreetmap wiki](https://wiki.openstreetmap.org/wiki/Key:roof:shape) or try using an area which already contains a dome or onion shape within (eg.  12.36902,51.33,12.37983,51.33721 ) and you'll be met with a Python AttributeError. 

```
Error: Python: Traceback (most recent call last):
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 250, in execute
    return self.importOsm(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 351, in importOsm
    a.render()
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/app/blender.py", line 464, in render
    m.render()
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/building/manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/building/renderer.py", line 135, in render
    self.renderElement(outline, building, osm)
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/building/renderer.py", line 164, in renderElement
    self._renderElement(element, building, roof, data, osm)
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/building/renderer.py", line 176, in _renderElement
    roof.render()
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/building/roof/mesh.py", line 94, in render
    Renderer.addForJoin(o, r.obj)
  File "/home/username/.config/blender/3.6/scripts/addons/blosm/renderer/__init__.py", line 143, in addForJoin
    join = self.toJoin
           ^^^^^^^^^^^
AttributeError: type object 'Renderer' has no attribute 'toJoin'
```

This bug affects the most recently available build of the free version of Blosm distributed on gumtree. Error has been replicated on both Windows 10 and Fedora Linux, both using Blender 3.6.4.

**Comment by vvoovv** [comment]
Hi @redactedUse 

Please try restarting Blender. If it didn't help, please try the following actions:
* Delete all previous versions of Blender-OSM or Blosm addon. There can be more than one of them. You can find them by typing `osm` in the search box in the Blender preferences.
* Restart Blender
* Install the latest version of the Blosm addon.

**Comment by redactedUse** [comment]
> Hi @redactedUse
> 
> Please try restarting Blender. If it didn't help, please try the following actions:
> 
>     * Delete all previous versions of Blender-OSM or Blosm addon. There can be more than one of them. You can find them by typing `osm` in the search box in the Blender preferences.
> 
>     * Restart Blender
> 
>     * Install the latest version of the Blosm addon.

This did indeed fix the issue but I've encountered it numerous times on different platforms. I'd be interested in knowing why the issue occurs if you happen to know.

**Comment by vvoovv** [comment]
Perhaps you had older version of the addon.

**Comment by redactedUse** [comment]
> Perhaps you had older version of the addon.

I believe it was a reinstall of the same version, I didn't download a new version of the addon. Regardless I'll close the issue and if I can figure out how to properly replicate it I'll create a new one that is more specific. Thank you for the quick reply
