### ISSUE TITLE
Context override not working when importing data

### ISSUE THREAD

**Issue by pebasantaf** [vvoovv/blender-geo#428]
I am having the issue that context seems not not really be overridden when call the command `bpy.ops.blosm.import_data()`. I have try both possibilities:
```
with bpy.context.temp_override(**ctx):
            bpy.ops.blosm.import_data()
```
and
```
bpy.ops.blosm.import_data(ctx)
```
Of course, the variable `ctx` is a dictionary with desired context parameters. 
In my call, I first run the import_data() command for terrain, which leads to no issues. The issue comes when I import the OSM building data.
Essentially, the code crashes at the moment of creating meshes in Blender related to the terrain envelope.
**Error message:**

Downloading the file from http://overpass-api.de/api/map?bbox=13.247733116149902,53.623653411865234,13.252266883850098,53.626346588134766...
Saving the file to /home/pebasantaf/blender_downloads/osm/map_14.osm...
Parsing OSM file /home/pebasantaf/blender_downloads/osm/map_14.osm...
Downloading data for incomplete OSM relations
Downloading the file from http://overpass-api.de/api/interpreter...
Saving the file to /home/pebasantaf/blender_downloads/osm/map_14_extra.osm...
Parsing and processing data from the file /home/pebasantaf/blender_downloads/osm/map_14_extra.osm for incomplete OSM relations
Time for parsing OSM file: 0:00:00.176251
Processing the parsed OSM data...
The number of buildings: 0
Time for processing of the parsed OSM data: 0:00:00.000031
Creating meshes in Blender...
Traceback (most recent call last):
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 250, in execute
    return self.importOsm(context)
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 351, in importOsm
    a.render()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/app/blender.py", line 460, in render
    r.prepare()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/renderer/curve_renderer.py", line 59, in prepare
    terrain.createEnvelope()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/terrain/__init__.py", line 157, in createEnvelope
    bpy.ops.mesh.select_all(action='DESELECT')
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/bpy/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.mesh.select_all.poll() failed, context is incorrect
Error: Python: Traceback (most recent call last):
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 250, in execute
    return self.importOsm(context)
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 351, in importOsm
    a.render()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/app/blender.py", line 460, in render
    r.prepare()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/renderer/curve_renderer.py", line 59, in prepare
    terrain.createEnvelope()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/terrain/__init__.py", line 157, in createEnvelope
    bpy.ops.mesh.select_all(action='DESELECT')
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/bpy/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.mesh.select_all.poll() failed, context is inco127.0.0.1 - - [07/Dec/2023 13:23:33] "GET /location?latitude=53.625&longitude=13.25 HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/flask/app.py", line 1478, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/flask/app.py", line 1458, in wsgi_app
    response = self.handle_exception(e)
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/pebasantaf/repositories/ems-shadowmap/main.py", line 43, in location
    bool_map = app.run(latitude, longitude, context=ctx)
  File "/home/pebasantaf/repositories/ems-shadowmap/application/app.py", line 51, in run
    map.importMapToBlender(**kwargs)
  File "/home/pebasantaf/repositories/ems-shadowmap/map/blosm_map.py", line 130, in importMapToBlender
    bpy.ops.blosm.import_data(ctx)
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/bpy/3.6/scripts/modules/bpy/ops.py", line 111, in __call__
    ret = _op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Error: Python: Traceback (most recent call last):
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 250, in execute
    return self.importOsm(context)
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/__init__.py", line 351, in importOsm
    a.render()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/app/blender.py", line 460, in render
    r.prepare()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/renderer/curve_renderer.py", line 59, in prepare
    terrain.createEnvelope()
  File "/home/pebasantaf/.config/blender/3.6/scripts/addons/blosm/terrain/__init__.py", line 157, in createEnvelope
    bpy.ops.mesh.select_all(action='DESELECT')
  File "/home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/bpy/3.6/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Operator bpy.ops.mesh.select_all.poll() failed, context is incorrect
Location: /home/pebasantaf/repositories/ems-shadowmap/.venv/lib/python3.10/site-packages/bpy/3.6/scripts/modules/bpy/ops.py:111

After doing some debugging in ops.py in the `__call__` method, I figured that the available context there was not the one I pass through import_data() to override it.
For context, I am running bpy within the context of a Flask API. This leads to the fact that the  initial import of the blender project through `bpy.ops.wm.open_mainfile(filepath=os.path.join(root_dir, r'project.blend'))` must be done outside the flask app @route definition. Placing it inside leads to a fragmentation error. As it is being placed outside, they operate in separate threads which leads me to need to use context_override every time I run a bpy.ops command. I understand this issue might be related to Linux itself and not only to Blosm, but the issue appears with `bpy.ops.blosm.import_data(ctx)`, and other ops commands can be successfully overridden. 
Let me know if you need more information, or if you consider that the Blender repo itself might be a better place to ask.

**Comment by vvoovv** [comment]
Hi @pebasantaf,

This problem does not seem to be related to the Blosm addon.
