### ISSUE TITLE
Big area OSM

### ISSUE THREAD

**Issue by dag08** [vvoovv/blender-geo#449]
Importing big areas comes with this errors below and there are just few buildings imported.
The coordinates are: 2.15957,48.78926,2.49245,48.93873

Parsing OSM file C:\Users\User\Desktop\paris.osm...
Parsing and processing data from the file C:\Users\User\Desktop\paris_extra.osm for incomplete OSM relations
Time for parsing OSM file: 0:02:10.190090
Processing the parsed OSM data...
The number of buildings: 585451
Time for processing of the parsed OSM data: 0:00:12.176905
Creating meshes in Blender...
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
Saved: F:\Projects\3D\Blender\OpenStreet\texture\1705051949\baked_duion_bricks_classic_02_D_exp.png_ffc0cb_pro_2901_exp0001.png
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
Saved: F:\Projects\3D\Blender\OpenStreet\texture\1705051949\baked_cc0textures_bricks11_col_exp.jpg_ff0000_pro_2901_exp0001.png
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
Saved: F:\Projects\3D\Blender\OpenStreet\texture\1705051949\baked_duion_concrete_rough_01_D_exp.png_afafaf_pro_2161_exp0001.png
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
OpenColorIO Error: DisplayViewTransform error. Display 'sRGB' not found.
Saved: F:\Projects\3D\Blender\OpenStreet\texture\1705051949\baked_duion_concrete_rough_01_D_exp.png_afafaf_pro_2157_exp0001.png
Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\__init__.py", line 250, in execute
    return self.importOsm(context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\__init__.py", line 351, in importOsm
    a.render()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\app\blender.py", line 464, in render
    m.render()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\building\manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\building2\renderer.py", line 156, in render
    action.do(building, itemClass, buildingStyle, self)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\__init__.py", line 93, in do
    self.generateVolume(footprint, element.getData(self.data))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\__init__.py", line 100, in generateVolume
    volumeGenerator.do(footprint, coords)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\roof.py", line 83, in do
    self.render(footprint, roofItem)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\roof_hipped.py", line 70, in render
    ok = self.generateRoof(footprint, roofItem, firstVertIndex)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\roof_hipped.py", line 225, in generateRoof
    polygonize(
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 999, in polygonize
    skeleton = skeletonize(edgeContours)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 872, in skeletonize
    output = mergeNodeClusters(output,edgeContours)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 677, in mergeNodeClusters
    source = tuple(i for i in p.source)
TypeError: 'NoneType' object is not iterable
Error: Python: Traceback (most recent call last):
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\__init__.py", line 250, in execute
    return self.importOsm(context)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\__init__.py", line 351, in importOsm
    a.render()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\app\blender.py", line 464, in render
    m.render()
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\building\manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\building2\renderer.py", line 156, in render
    action.do(building, itemClass, buildingStyle, self)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\__init__.py", line 93, in do
    self.generateVolume(footprint, element.getData(self.data))
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\__init__.py", line 100, in generateVolume
    volumeGenerator.do(footprint, coords)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\roof.py", line 83, in do
    self.render(footprint, roofItem)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\roof_hipped.py", line 70, in render
    ok = self.generateRoof(footprint, roofItem, firstVertIndex)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\action\volume\roof_hipped.py", line 225, in generateRoof
    polygonize(
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 999, in polygonize
    skeleton = skeletonize(edgeContours)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 872, in skeletonize
    output = mergeNodeClusters(output,edgeContours)
  File "C:\Users\User\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 677, in mergeNodeClusters
    source = tuple(i for i in p.source)
TypeError: 'NoneType' object is not iterable

**Comment by vvoovv** [comment]
The error is caused by a specific building with the hipped roof. 

Since your area of interest is huge, we would appreciate if help localizing the problem, i.e. finding a significantly smaller area where the error occurs.

You can deactivate the experimental method and hipped roofs won't be generated.
