### ISSUE TITLE
Inconsistent Behaviour

### ISSUE THREAD

**Issue by ohadmanor** [vvoovv/blender-geo#558]
Hi,

I have strange behavior (I try everything to debug it):

When I use the following coordinate everything works perfect: maxLat = 31.309, minLat = 31.303, maxLon = 35.29, minLon = 35.26

But when I change to: 31.309, minLat = 31.303, maxLon = **35.3**, minLon = 35.26 I get the following error:

Python: Traceback (most recent call last):
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\__init__.py", line 256, in execute
    return self.importOsm(context)
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\__init__.py", line 357, in importOsm
    a.render()
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\app\blender.py", line 488, in render
    m.render()
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\building\manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\building2\renderer.py", line 156, in render
    action.do(building, itemClass, buildingStyle, self)
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\action\volume\__init__.py", line 93, in do
    self.generateVolume(footprint, element.getData(self.data))
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\action\volume\__init__.py", line 100, in generateVolume
    volumeGenerator.do(footprint, coords)
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\action\volume\roof.py", line 83, in do
    self.render(footprint, roofItem)
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\action\volume\roof_hipped.py", line 70, in render
    ok = self.generateRoof(footprint, roofItem, firstVertIndex)
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\action\volume\roof_hipped.py", line 225, in generateRoof
    polygonize(
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 1053, in polygonize
    embedding = graph.circular_embedding(verts,'CCW')
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in circular_embedding
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in <lambda>
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 18, in compare_angles
    a1 = pseudoangle(vList[p1] - vList[center])
  File "C:\Develop\3DTiles\blender\3.6\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 11, in pseudoangle
    p = d[0]/(abs(d[0])+abs(d[1])) # -1 .. 1 increasing with x
ZeroDivisionError: float division by zero

**Comment by vvoovv** [comment]
Hi @ohadmanor 

Unfortunately I can't reproduce your problem.

**Comment by ohadmanor** [comment]
I try to use the original coordinate that cause the broblem with the latest versions: Blender 4.3, Blosm 2.7.11, and as you can see I get the error. any Idea?

![image](https://github.com/user-attachments/assets/b28dc6d7-c9e3-424f-b873-f3d9a6d99691)

**Comment by mariusvn** [comment]
@vvoovv  i have the same issue in vancouver import with a terrain.

```
Traceback (most recent call last):
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\__init__.py", line 251, in execute
    return self.importOsm(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\__init__.py", line 352, in importOsm
    a.render()
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\app\blender.py", line 483, in render
    m.render()
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\building\manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\building2\renderer.py", line 156, in render
    action.do(building, itemClass, buildingStyle, self)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\__init__.py", line 93, in do
    self.generateVolume(footprint, element.getData(self.data))
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\__init__.py", line 100, in generateVolume
    volumeGenerator.do(footprint, coords)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\roof.py", line 83, in do
    self.render(footprint, roofItem)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\roof_hipped.py", line 70, in render
    ok = self.generateRoof(footprint, roofItem, firstVertIndex)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\roof_hipped.py", line 225, in generateRoof
    polygonize(
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 1053, in polygonize
    embedding = graph.circular_embedding(verts,'CCW')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in circular_embedding
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in <lambda>
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 18, in compare_angles
    a1 = pseudoangle(vList[p1] - vList[center])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 11, in pseudoangle
    p = d[0]/(abs(d[0])+abs(d[1])) # -1 .. 1 increasing with x
        ~~~~^^~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
Error: Python: Traceback (most recent call last):
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\__init__.py", line 251, in execute
    return self.importOsm(context)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\__init__.py", line 352, in importOsm
    a.render()
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\app\blender.py", line 483, in render
    m.render()
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\building\manager.py", line 81, in render
    self.renderer.render(building, self.data)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\building2\renderer.py", line 156, in render
    action.do(building, itemClass, buildingStyle, self)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\__init__.py", line 93, in do
    self.generateVolume(footprint, element.getData(self.data))
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\__init__.py", line 100, in generateVolume
    volumeGenerator.do(footprint, coords)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\roof.py", line 83, in do
    self.render(footprint, roofItem)
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\roof_hipped.py", line 70, in render
    ok = self.generateRoof(footprint, roofItem, firstVertIndex)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\action\volume\roof_hipped.py", line 225, in generateRoof
    polygonize(
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\bpypolyskel.py", line 1053, in polygonize
    embedding = graph.circular_embedding(verts,'CCW')
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in circular_embedding
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 60, in <lambda>
    ordering = sorted(neighbors, key = cmp_to_key( lambda a,b: compare_angles(vList,a,b,vertex)) )
                                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 18, in compare_angles
    a1 = pseudoangle(vList[p1] - vList[center])
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mariu\AppData\Roaming\Blender Foundation\Blender\4.5\scripts\addons\blosm\lib\bpypolyskel\poly2FacesGraph.py", line 11, in pseudoangle
    p = d[0]/(abs(d[0])+abs(d[1])) # -1 .. 1 increasing with x
        ~~~~^^~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero
```

Blender 4.5.3 LTS
Blosm 2.7.14

imported coordinates: -123.26626,49.11029,-123.04035,49.29602
3D realistic
i created a terrain with external tools and used it as blosm terrain


It worked with other cities before, for some reasons, this one is broken

<img width="249" height="648" alt="Image" src="https://github.com/user-attachments/assets/ae8f75e0-d38a-4e9a-ab85-18f8cd106522" />


**EDIT:**

apparently its just the downtown part of Vancouver that is affected. if i download everything around it does work. maybe its some broken osm data

<img width="1905" height="901" alt="Image" src="https://github.com/user-attachments/assets/ec7f7b0b-f293-4064-bccc-802da24f06dc" />

**EDIT 2:**

the problem is in this very small bbox -123.13835,49.28431,-123.13444,49.28638

**Comment by vvoovv** [comment]
Hi @mariusvn 

Thank you for reporting the problem. It's caused by this [building](https://www.openstreetmap.org/way/312686722). The error is not reproduced if one imports just this building. Mostly like the error is caused by a floating point precision error.

A walk-around for now is to import relative to this building. In Blender's Python Console execute:
```python
C.scene["lon"] = -123.1375609
C.scene["lat"] = 49.2850724
```
That sets the coordinates of Blender's system of reference. This point lies on the building footprint.
Then import your area of interest again,

I'll investigate how the problem can be fixed.
